enum PAYMENT_METHOD {
    PAYPAL_STANDARD = "PAYPAL_STANDARD",
    PAYPAL_BCDC = "PAYPAL_BCDC",
    PAYPAL_APM = "PAYPAL_APM",
    PAYPAL_BNPL = "PAYPAL_BNPL",
    PAYPAL_ACDC = "PAYPAL_ACDC",
    PAYPAL_GOOGLEPAY = 'PAYPAL_GOOGLEPAY',
    PAYPAL_APPLEPAY = 'PAYPAL_APPLEPAY',

}

export default PAYMENT_METHOD;
